name: duan
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  iconsax: ^0.0.8
  intl: any

  cupertino_icons: ^1.0.6
  page_transition: ^2.1.0
  floating_action_bubble: ^1.1.4

  async: ^2.11.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  http: ^1.2.1

  path_provider: ^2.1.3
  path: ^1.9.0
  file_picker: ^8.0.4
  image_picker: ^0.8.5+3
  multi_image_picker_view: ^1.0.0

  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  sqflite: ^2.2.6


#  flutter_form_builder: ^9.2.1 # Cập nhật phiên bản này
#  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/files/
